### PR TITLE
Laravel Version Migration from 4.1.31 (Current) To Laravel Version 5.1 (Latest). 

### PR DESCRIPTION
**Pull request by vrkansagara**
In this PR Laravel version migration from current to the Laravel latest version 5.1.
There are minor changes are applied with this PR.
And With ref to the issue #106 . I would like to request the Repository owner as per recent chat on issue #63 

> Please open a PR @vrkansagara – if your first PR looks good, I will add you as a contributor.

And 

> Yes, although I don't agree that the title of the README necessarily needs changing.
> Basically what I'm looking for is that you're a serious contributor to the project, who's going to keep it well maintained, writing good code, and I can only ascertain this once you've had a handful of pull requests merged into the project.
> The whole reason for pull requests is that we keep MoA's code well structured, well maintained. If we allowed everybody to commit directly to the master branch, then the project would soon get out of hand with — for example — people committing breaking changes, which then affects everybody else, making it more work for other contributors to reverse those changes.

Review this PR and look forwards for the project collaboration and contributor.

Ping +1: @Wildhoney and @aonic

### CODE REVIEW

**Comment by vrkansagara** [comment]
@Wildhoney  Have you reviewed this PR.

**Comment by Wildhoney** [comment]
@vrkansagara looks awesome! :+1: Give me a chance to review it though, and would also be nice to get feedback from @aonic, if possible.

**Comment by aonic** [comment]
I'll review this as wel

**Comment by vrkansagara** [comment]
@aonic  and @Wildhoney  Why it's take a long time to review on this PR. Does this repository is old enough that you are not watching it.

**Comment by aonic** [comment]
@vrkansagara its a really big PR -- and with a lack of proper automated tests its an involved process to check everything is working as before.

**Comment by vrkansagara** [comment]
@aonic  @Wildhoney  Ping :-1:  https://github.com/Wildhoney/Magento-on-Angular/issues/63#issuecomment-172825944

**Comment by aonic** [comment]
Hi @vrkansagara has this PR been tested by you to work just like the old version of Laravel did in reference to how it communicates with the Angular FE?

**Comment by vrkansagara** [comment]
@aonic  I personally think that some of contributor not interested to review on the PR which is already opened specially for the migrated code. and Yes for the angular FE I haven't changed anything.

**Comment by vrkansagara** [comment]
Author has no satisfactory response on this PR till date so closing this out and no more contribution towards this project.  Am sorry :-1: 

Author might not want to give credit for the contribution. :-1:  :-1:  :-1:

**Pull request closed without merging**
